--CONSULTAS

--LLENADO DIM_PLAN 
SELECT ID_PLAN, NOMBRE, PRECIO FROM PLANES;

--LLENADO DIM_USUARIO
SELECT ID_USUARIO, NOMBRE_USUARIO, ID_PLAN FROM USUARIOS;

--LLENADO DIM_LISTA REPRODUCCION
SELECT ID_LISTA, NOMBRE, ID_USUARIO FROM LISTAS_REPRODUCCION;

--LLENADO DIM_GENERO_MUSICAL
SELECT ID_GENERO, NOMBRE_GENERO FROM GENEROS_MUSICALES;

--LLENADO DIM_ARTISTA
SELECT ID_ARTISTA, NOMBRE FROM ARTISTAS;

--LLENADO DIM_GRUPO
SELECT ID_GRUPO, NOMBRE FROM GRUPOS;

--LLENADO DIM_CANCION
SELECT ID_CANCION, ID_ARTISTA, ID_GRUPO, ID_GENERO, TITULO, DURACION_SEGUNDOS FROM CANCIONES;

--LLENADO DIM_TIEMPO

SELECT CONVERT(DATE, A.FECHA_REPRODUCCION) Id_tiempo,
    DATEPART(YEAR, CAST(A.FECHA_REPRODUCCION AS DATE)) AS ANIO,
    DATEPART(month, CAST(A.FECHA_REPRODUCCION AS DATE)) AS MES,
    DATEPART(week, CAST(A.FECHA_REPRODUCCION AS DATE)) AS SEMANA,
    DATEPART(quarter, CAST(A.FECHA_REPRODUCCION AS DATE)) AS TRIMESTRE,
    CASE
        WHEN MONTH(CAST(A.FECHA_REPRODUCCION AS DATE)) BETWEEN 1 AND 4 THEN 1
        WHEN MONTH(CAST(A.FECHA_REPRODUCCION AS DATE)) BETWEEN 5 AND 8 THEN 2
        WHEN MONTH(CAST(A.FECHA_REPRODUCCION AS DATE)) BETWEEN 9 AND 12 THEN 3
    END AS CUATRIMESTRE,
    DATENAME(weekday, CAST(A.FECHA_REPRODUCCION AS DATE)) AS DIA_SEMANA
FROM REPRODUCCIONES A        
GROUP BY A.fecha_reproduccion

--LLENADO HECHOS
	SELECT 
    r.id_usuario,
    r.id_cancion,
    CAST(CONVERT(VARCHAR(8), r.fecha_reproduccion, 112) AS INT) AS id_fecha,
    COUNT(*) AS cantidad_reproducciones,
    SUM(r.duracion_reproduccion_segundos) AS total_duracion_segundos
FROM reproducciones r2
WHERE r.fecha_reproduccion IS NOT NULL
GROUP BY 
    r.id_usuario,
    r.id_cancion,
    CAST(CONVERT(VARCHAR(8), r.fecha_reproduccion, 112) AS INT);


SELECT 
    r.id_usuario,
    r.id_cancion,
    CAST(CONVERT(VARCHAR(8), r.fecha_reproduccion, 112) AS INT) AS id_fecha,
    COUNT(*) AS cantidad_reproducciones,
    SUM(r.duracion_reproduccion_segundos) AS total_duracion_segundos
FROM reproducciones r
WHERE r.fecha_reproduccion IS NOT NULL
GROUP BY 
    r.id_usuario,
    r.id_cancion,
    CAST(CONVERT(VARCHAR(8), r.fecha_reproduccion, 112) AS INT);
